services:
  model-service:
    build:
      context: .
      dockerfile: dockerfile_model.dockerfile
    container_name: model-container
    ports:
      - "5000:5000"
    volumes:
      - ./model.pth:/app/model.pth  # Make sure the model is available
    networks:
      - app-network

  streamlit-app:
    build:
      context: .
      dockerfile: dockerfile_streamlit.dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - model-service
      - postgres-db
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/logging_db  # Connection string
    networks:
      - app-network
  
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: logging_db  # Database name
      POSTGRES_USER: postgres   # Database user
      POSTGRES_PASSWORD: password  # Database password
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount the init script
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:  # Named volume to persist PostgreSQL data
